@startuml
skinparam ClassAttributeIconSize 0

package "model" {

    
    interface IUI as "UI" {
        + {abstract} MakeMainWindow()
    }

    interface IGGraph as "GGraph" {
        + {abstract} SetSimpleAdjMatrix(AdjMatrix)
        + {abstract} SetDirectedAdjMatrix(AdjMatrix)
        + {abstract} Show()
    }

    interface IConfig as "Config" {
        + {abstract} Load()
        + {abstract} Save()
    }

    interface IManager as "Manager" {
        + {abstract} Init()
        + {abstract} Start()
    }

}

note "интерфейс для\n управления программой" as N1
N1 .. IManager  
    
package "internal" {

    package "ui" {
        class uigraph {
            + MakeMainWindow() ui.UI
        }
    }
    IUI <|-- uigraph

    package "config" {
        class config {
            + Load()
            + Save()
        }
    }
    IConfig <|-- config

    package "ggraph" {
        class ggraph{
            + SetAdjMatriz()
            + Show()
        }
    }
    IGGraph  <|-- ggraph

    package "manager" {
        class manager{
            + Init(UI)
            + Start()
        }
    }
    IManager <|-- manager
    ggraph  <..* manager
    
}

package "app" {

    interface IApp as "Application" {
        + {abstract} Config()
        + {abstract} Start()
    }

    class AppGraph{
        config model.Config
	    manag  model.Manager
	    gui    model.UI
    }
    IApp <|--AppGraph

    manager <..* AppGraph
    uigraph <..* AppGraph
    config  <..* AppGraph
    
}

package gui as "ui" {

    interface IGui as "UI" {
        + {abstract} Show()
    }

    class formain {
        - init()
        + Show()
    }
    IGui  <|-- formain 
    IGui  <..o uigraph  
    uigraph  ..formain 
}


@enduml
