@startuml
skinparam ClassAttributeIconSize 0

package "model" {

    interface IGGraph as "GGraph" {
        + {abstract} SetSimpleAdjMatrix(AdjMatrix)
        + {abstract} SetDirectedAdjMatrix(AdjMatrix)
        + {abstract} Show()
    }

    interface IConfig as "Config" {
        + {abstract} Load()
        + {abstract} Save()
    }

    interface IManager as "Manager" {
        + {abstract} Init()
        + {abstract} Start()
    }

    interface IUIBase as "UIBase" {
        + {abstract} Show()
    }

    interface IGUIFactory as "GUIFactory"{
        +{abstract}MakeMainWindow() UIFormMain
    }

    interface IUIFormMain as "UIFormMain" {
        +{abstract} model.UIBase
        +{abstract} Init(manag model.Manager)
        +{abstract} SetSimpleAdjMatrix(adm AdjMatrix)
    }
    IUIBase <|-- IUIFormMain 

}

note "интерфейс для\n управления программой" as N1
N1 .. IManager  
    
package "internal" {

    package "config" {
        class config {
            + Load()
            + Save()
        }
    }
    IConfig <|-- config

    package "ggraph" {
        class ggraph{
            + SetAdjMatriz()
            + Show()
        }
    }
    IGGraph  <|-- ggraph

    package "manager" {
        class manager{
            + Init()
            + Start()
        }
    }
    IManager <|-- manager
    ggraph  <..* manager
    
}

package gui as "gui" {

    class formain {
        + Init(manag model.Manager)
        + SetSimpleAdjMatrix(adm AdjMatrix)
        + Show()
    }
    IUIFormMain <|-- formain 
    
    class guifactory {
        + MakeMainWindow() IUIFormMain
    }
    IGUIFactory <|-- guifactory
    formain <.. guifactory
}


package "app" {

    interface IApp as "Application" {
        + {abstract} Config()
        + {abstract} Start()
    }

    class AppGraph{
        config model.Config
	    manag  model.Manager
	    gui    UI
    }
    IApp <|--AppGraph

    manager <..* AppGraph
    config  <..* AppGraph
    guifactory <..*AppGraph
    
}

package cmd {
    class main {
        App.Config()
        App.Start()
    }
    IApp <--*main
}

@enduml
